---
version: '3.8'
services:
  db:
    image: viswanathkasi/dummy:db
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    networks:
      - db_network
      - service
    volumes:
      - db_volume:/docker-entrypoint-initdb.d/:ro

  auth_service:
    image: viswanathkasi/dummy:auth
    ports:
      - "5001:5001"
    deploy:
      replicas: 3
    networks:
      - service
      - db_network
      - frontend
    volumes:
      - auth_volume:/app:ro
       
  book_service:
    image: viswanathkasi/dummy:book
    ports:
      - "5002:5002"
    deploy:
      replicas: 3
    networks:
      - service
      - db_network
      - frontend
    volumes:
      - book_volume:/app:ro

  borrow_service:
    image: viswanathkasi/dummy:borrow
    ports:
      - "5003:5003"
    deploy:
      replicas: 3
    networks:
      - service
      - db_network
      - frontend
    volumes:
      - borrow_volume:/app:ro
     
  frontend:
    image: viswanathkasi/dummy:frontend
    ports:
      - "8081:5000"
    deploy:
      replicas: 3
    networks:
      - frontend
      - service
    volumes:
      - frontend_volume:/app:ro
    
volumes:
  db_volume:
  auth_volume:
  book_volume:
  borrow_volume:
  frontend_volume:
networks:
  db_network:
    driver: overlay
  service:
    driver: overlay
  frontend:
    driver: overlay
...
