---
version: '3.8'
services:
  db:
    image: viswanathkasi/docker-stack-project-db
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    networks:
      - db_network
      - service
    volumes:
      - db_volume:/docker-entrypoint-initdb.d/:ro
    environment:
      AUTH__URL: http://flm_auth_service:5001
      BOOK_URL: http://flm_book_service:5002
      BORROW_URL: http://flm_borrow_service:5003

  auth_service:
    image: viswanathkasi/docker-stack-project-auth
    ports:
      - "5001:5001"
    deploy:
      replicas: 3
    networks:
      - service
      - db_network
      - frontend
    volumes:
      - auth_volume:/app:ro
    environment:
      DB_HOST: flm_db:3306
      BOOK_URL: http://flm_book_service:5002
      BORROW_URL: http://flm_borrow_service:5003
       
  book_service:
    image: viswanathkasi/docker-stack-project-book
    ports:
      - "5002:5002"
    deploy:
      replicas: 3
    networks:
      - service
      - db_network
      - frontend
    volumes:
      - book_volume:/app:ro
    environment:
      DB_HOST: flm_db:3306
      AUTH_URL: http://flm_auth_service:5001
      BORROW_URL: http://flm_borrow_service:5003

  borrow_service:
    image: viswanathkasi/docker-stack-project-borrow
    ports:
      - "5003:5003"
    deploy:
      replicas: 3
    networks:
      - service
      - db_network
      - frontend
    volumes:
      - borrow_volume:/app:ro
    environment:
      DB_HOST: flm_db:3306
      AUTH_URL: http://flm_auth_service:5001
      BOOK_URL: http://flm_book_service:5002
     
  frontend:
    image: viswanathkasi/docker-stack-project-frontend
    ports:
      - "85:5000"
    deploy:
      replicas: 3
    networks:
      - frontend
      - service
    volumes:
      - frontend_volume:/app:ro
    environment:
      AUTH_URL: http://flm_auth_service:5001
      BOOK_URL: http://flm_book_service:5002
      BORROW_URL: http://flm_borrow_service:5003
    
volumes:
  db_volume:
  auth_volume:
  book_volume:
  borrow_volume:
  frontend_volume:
networks:
  db_network:
    driver: overlay
  service:
    driver: overlay
  frontend:
    driver: overlay
...
