---
version: '3.8'
services:
  db:
    container_name: db
    build: ./database/
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    networks:
      - db_network
      - service
    volumes:
      - db_volume:/docker-entrypoint-initdb.d/:ro

  auth:
    container_name: auth_service
    build: ./auth/
    ports:
      - "5001:5001"
    deploy:
      replicas: 1
    networks:
      - service
      - db_network
      - frontend
    volumes:
      - auth_volume:/app:ro
       
  book:
    container_name: book_service
    build: ./book/
    ports:
      - "5002:5002"
    deploy:
      replicas: 1
    networks:
      - service
      - db_network
      - frontend
    volumes:
      - book_volume:/app:ro

  borrow:
    container_name: borrow_service
    build: ./borrow/
    ports:
      - "5003:5003"
    deploy:
      replicas: 1
    networks:
      - service
      - db_network
      - frontend
    volumes:
      - borrow_volume:/app:ro
     
  frontend:
    container_name: frontend
    build: .
    ports:
      - "86:5000"
    deploy:
      replicas: 1
    networks:
      - frontend
      - service
    volumes:
      - frontend_volume:/app:ro      
volumes:
  db_volume:
  auth_volume:
  book_volume:
  borrow_volume:
  frontend_volume:
networks:
  db_network:
    driver: bridge
  service:
    driver: bridge
  frontend:
    driver: bridge
...
